### ISSUE TITLE
Missing Settings.

### ISSUE THREAD

**Issue by lolle202** [loki79uk/FS25_LumberJack#1]
Hi, the mod is now out in the Modhub, but I don't see the setting where I can change the cutting speed.

**Comment by loki79uk** [comment]
See the front page for the release - you need to change the xml in your mod settings folder:
https://github.com/loki79uk/FS25_LumberJack/releases/tag/v1.0.0.0

**Comment by loki79uk** [comment]
Closing as duplicate of #3 

_I will add a menu as soon as I can work out how!  All of the methods that I used in FS22 cause game breaking errors now.. lol_

**Comment by loki79uk** [comment]
Sorry - I totally missed that this was not being set.  Please try the latest one:
https://github.com/loki79uk/FS25_LumberJack/releases
