### ISSUE TITLE
Unable to get mod working

### ISSUE THREAD

**Issue by tmelloorr** [loki79uk/FS25_LumberJack#2]
I've been trying for a while to get this mod working, but I cannot seem to get any part of it active on my existing save game.  Looking at the logs I get this error:

`2024-11-22 18:33 LumberJack - FATAL ERROR: C:/Users/Tom/Documents/My Games/FarmingSimulator2025/mods/FS25_LumberJack/LumberJack.lua:685: attempt to concatenate nil with string`

Not sure if this is causing to mod to completely fail?

**Comment by loki79uk** [comment]
Sorry! It seems that no one tested it on the Asian map, including me or GIANTS..

Should be fixed now in: https://github.com/loki79uk/FS25_LumberJack/releases/tag/v1.0.0.1

**Comment by loki79uk** [comment]
It was this meadows layer:
![image](https://github.com/user-attachments/assets/98e6f240-dbd6-4889-91cf-cf862f28819e)

**Comment by tmelloorr** [comment]
Oh! Thanks for the quick fix, it works now.

Why do I get the feeling this is more of an issue with the map, than with the mod itself 😅

**Comment by AKF2996** [comment]
Has cut duration/chainsaw speed been implemented yet? If so, what settings in the LUA do I need to edit to increase chainsaw speed/ decrease cut duration? Genuinely, thank you for all your work.

**Comment by loki79uk** [comment]
> Has cut duration/chainsaw speed been implemented yet? If so, what settings in the LUA do I need to edit to increase chainsaw speed/ decrease cut duration? Genuinely, thank you for all your work.

You need to change in the mod settings XML for now.  I've put instructions on the front page/main readme.  I will work on adding the menu again as soon as I can after getting UAL released!

**Comment by Baker-CODE** [comment]
> > Has cut duration/chainsaw speed been implemented yet? If so, what settings in the LUA do I need to edit to increase chainsaw speed/ decrease cut duration? Genuinely, thank you for all your work.
> 
> You need to change in the mod settings XML for now. I've put instructions on the front page/main readme. I will work on adding the menu again as soon as I can after getting UAL released!

which file is that in? was looking at the other issue and wasnt able to find the file that has those lines in it.

**Comment by loki79uk** [comment]
Just a comment for anyone who is interested:  as embarasing as it was to have a bug like that on release - it was a good test/demonstration that my idea for preventing infinite log entries actually worked.. i.e. it was only mod-breaking and NOT game breaking!

https://github.com/loki79uk/FS25_LumberJack/blob/aa9e2f133efc4484d42b9257b97d7c28fc103603/LumberJack.lua#L1019-L1035

**Comment by loki79uk** [comment]
Closing as fixed
