### ISSUE TITLE
Could not register Controls with the Focus manager Spamming client log

### ISSUE THREAD

**Issue by FrmrJon** [loki79uk/FS25_LumberJack#21]
We just downloaded the latest release of lumberjack for server and client, which on the Github said it was 1.0.0.4, but on the server and in the ModDesc it still says 1.0.0.3. After downloading the latest when I'm in the player settings page, It's spamming my log with a bunch of warnings. I've attached my Client log so you can see the warnings. For now we've gone back to 1.0.0.3, and warnings are gone.
[log.txt](https://github.com/user-attachments/files/17971476/log.txt)

**Comment by loki79uk** [comment]
Thanks for reporting - I tested this on a dedicated server and didn't see anything like this in the log.  Are you using player hosted MP, or a dedicated server?  I will investigate this evening and update here.

**Comment by FrmrJon** [comment]
We are using a dedicated server hosted on another pc on my network.

**Comment by FrmrJon** [comment]
I just saw the update. I will try it out.

**Comment by loki79uk** [comment]
Thanks - I forgot to mention the bug in the commit
