### ISSUE TITLE
Running LUA method 'packetReceived'.

### ISSUE THREAD

**Issue by JimmyBeam1990** [loki79uk/FS25_LumberJack#22]
Moin, Der fehler kommt in der Log im Dedi. MP, es fühlt sich nciht an das man eingeschränkt ist oder das etwas blockiert wird, aber ich dachte ich melde das mal.

2024-12-02 13:00 Error: Running LUA method 'packetReceived'.
C:/Users/tLabe/Documents/My Games/FarmingSimulator2025/mods/FS25_LumberJack/events/ToggleSawdustEvent.lua:30: attempt to index nil with 'setState'

**Comment by loki79uk** [comment]
Hi, I think this is a result of one of the pull requests the other day not matching something I changed.  I'll check this evening and update here.

**Comment by loki79uk** [comment]
Closing as stale.

**Comment by JimmyBeam1990** [comment]
sorry, der fehler war die version, mit der neueren war es wieder gefixt
