### ISSUE TITLE
Remaining Conflict/Collision after stump removal

### ISSUE THREAD

**Issue by streaky73** [loki79uk/FS25_LumberJack#24]
After removing a stump using the chainsaw with the Lumberjack mod , players are unable to terraform or place objects in the area where the stump was located. The issue has been tested on multiple fresh saves, comparing both the base game mulcher and the Lumberjack mod chainsaw removal. The problem only occurs when using the Lumberjack chainsaw - the base game mulcher works correctly.

Attempted to Investigate using various debug menus and views showed no visible lingering collisions or obvious causes for the issue.

Steps to reproduce:
1. Remove a stump using the Lumberjack chainsaw
2. Attempt to terraform or place objects in the cleared area
3. Note that the area remains blocked (often "Area is Restricted " warning) despite visual confirmation of stump removal

**Comment by loki79uk** [comment]
Thanks. I will look into this.

**Comment by loki79uk** [comment]
So if you have GIANTS version of the game it looks like you can try the latest release..  Otherwise on STEAM (for me) it still doesn't work..  I have no idea what is going on anymore...

**Comment by loki79uk** [comment]
Please try the latest release, I think it actually works now!
https://github.com/loki79uk/FS25_LumberJack/releases

**Comment by streaky73** [comment]
Confirmed that the issue is resolved on my end!

**Comment by loki79uk** [comment]
I should add a note, if anyone wants to fix an area on their exisiting savgame:
1) start game with -cheats flag
2) got to area affected
3) use console command `gsTipCollisionsUpdate`

**Comment by DeeDeeRanged** [comment]
Nice I've added that command to my list ;)
