### ISSUE TITLE
Won't save "Chainsaw Cut Distance" setting above 10 meters

### ISSUE THREAD

**Issue by carriganjosh** [loki79uk/FS25_LumberJack#26]
The max setting it will retain is 10 meters in the UI.  I've tried setting the value manually in the XML with no luck.

**Comment by loki79uk** [comment]
So in FS22 there were some other parameters than just the maxCutDistance:
```
	hTool.maxCutDistance = LumberJack.originalMaxCutDistance
	hTool.maxModelTranslation = LumberJack.originalMaxModelTranslation
	hTool.cutDetectionDistance = LumberJack.originalCutDetectionDistance
```

But in FS25, I can't find those or anything similar..  They changed cut distance to:
```
HandToolChainsaw.MAXIMUM_CUT_DISTANCE
```

So there must be some other parameters somewhere - I will try to find them!

**Comment by loki79uk** [comment]
Actually it is worse than I thought, it is not updating the distance at all.  The value that is loaded at the start of the game is permanent until the next restart.

**Comment by carriganjosh** [comment]
works great now!
