### ISSUE TITLE
error when downing tree

### ISSUE THREAD

**Issue by DanL58** [loki79uk/FS25_LumberJack#27]
![error](https://github.com/user-attachments/assets/45acbbaf-d2b4-4d4f-9e49-2d5259a2c45c)

Sorry for posting an issue when I'm not sure it is related to Lumberjack. I am very intermittently getting this error when cutting a tree. Sometimes it happens on the first tree in a session and sometimes I can cut for long time without it happening. It doesn't seem to matter what kind of tree I am cutting. When it happens the only thing that will let me continue is to quit & restart my save. I am also using Forestry Helper mod but I can't be sure it is related. There are no errors in the log. Any ideas? Thank you

**Comment by loki79uk** [comment]
I can't find any of those words in the base game messages.  I'll ask FarmsimTim if he knows anything about it.

**Comment by DanL58** [comment]
Thank you Loki, I see that Tim has already been aware of this issue and is making an update for it.
