### ISSUE TITLE
Ver. 1.1.0.0 at didicated Server

### ISSUE THREAD

**Issue by bpNetwork** [loki79uk/FS25_LumberJack#29]
When I activate the mod on my multiplayer server, I get an error message.
If I ignore this and go into the game, I cannot activate the mod.

Error on server: Unknown file type 'README.md'

**Comment by loki79uk** [comment]
I didn't actually mean to inlcude the readme file, but that doesn't stop it loading on my dedicated server.  I'll make a release without it now anyway.

**Comment by bpNetwork** [comment]
v1.0.0.0 works fine.

THANKS ;-)
