### ISSUE TITLE
Modifying Chainsaw Cut Duration

### ISSUE THREAD

**Issue by AKF2996** [loki79uk/FS25_LumberJack#3]
Has cut duration/chainsaw speed been implemented yet? If so, what settings in the LUA do I need to edit to increase chainsaw speed/ decrease cut duration? Genuinely, thank you for all your work.

**Comment by loki79uk** [comment]
I replied to the other comment, but edit the file in:
`%HOMEPATH%\Documents\My Games\FarmingSimulator2025\modSettings\LumberJack.xml`

Then start the game, or reload with console command
`lumberjackLoadSettings`

![image](https://github.com/user-attachments/assets/16b10836-8b2b-41fa-83a0-93509cd4c77f)

**Comment by AKF2996** [comment]
Thank you! I'll give that a go. I was scanning the LUA but couldn't identify the specific line to edit to adjust the cut speed.

**Comment by AKF2996** [comment]
I'm embarrassed to say I'm still not having any luck influencing the cut duration/speed. I tried the settings from the above screenshot but saw no change. I then tried adding "<defaultCutDuration value="4"/>" to the mod settings and still had no change.

**Comment by loki79uk** [comment]
Sorry it is a bug, let me check!

**Comment by loki79uk** [comment]
It was just straight up missing from the settings!
https://github.com/loki79uk/FS25_LumberJack/releases

**Comment by AKF2996** [comment]
Legend, thanks for sticking with me. Appreciate all you do.

**Comment by loki79uk** [comment]
> Legend, thanks for sticking with me. Appreciate all you do.

I'm sorry I missed it in the first place - my head was a bit all over the place with the Asian map bug, and working on Autoload at the same time, etc..

Closing as fixed.
