### ISSUE TITLE
Console support

### ISSUE THREAD

**Issue by Bird87ZA** [loki79uk/FS25_LumberJack#30]
Just a question as I'm not sure how complex it is.

Would it be possible to add console support to your mods?

**Comment by loki79uk** [comment]
Sorry, that is up to the agreement between GIANTS and Sony/Microsoft.  It is their decision to not allow script mods on console, there is nothing I can do about it.

**Comment by Bird87ZA** [comment]
Ah I see. Bugger! Thank you.
