### ISSUE TITLE
the mod does not work

### ISSUE THREAD

**Issue by Shampuur** [loki79uk/FS25_LumberJack#37]
Mod is not visible in the mod list in the game. 
I put the mod in the right folder, I didn’t repack anything.
other mods work.
I also tried to remove all mods and leave only this one.

tried on versions 1.1.1.0 and 1.1.2.0

Thank you.

**Comment by loki79uk** [comment]
I think if it "didn't work" then one of the 500,000 other people would have noticed by now.  Are you using the actual zip file from the release instead of the source code?  You could also just get it from the official ModHub.

**Comment by Shampuur** [comment]
I understand that most likely this is some kind of problem with me. I downloaded the release and installed it the same way as other mods, I just put it in the mods folder.  when I enter the game, that mod is not there. it does not work in the game. I tried on two computers. maybe it depends on the version of the game?

**Comment by loki79uk** [comment]
> I understand that most likely this is some kind of problem with me. I downloaded the release and installed it the same way as other mods, I just put it in the mods folder.  when I enter the game, that mod is not there. it does not work in the game. I tried on two computers. maybe it depends on the version of the game?

Ah yes, you probably need to update your game.  This is due to GIANTS requirement that the version number in the moddesc must match their latest one for any ModHub release.

You can also just edit your local copy inside the zip file. Set as 92 to be safe.

**Comment by Shampuur** [comment]
thank you, everything works
